### ISSUE TITLE
Re-organize ZK-Kit packages

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-kit#282]
**Description**

The current ZK-Kit provides several packages in different languages: Solidity, JavaScript, Circom, Noir. Although having everything in one repo can give you more control, managing several languages is still complex and makes CI and devtooling more difficult to configure.

Following internal conversations, the most widely accepted proposal was to have one zk-kit repository per language: zk-kit(.js), zk-kit.circom, zk-kit.sol, zk-kit.noir.

In addition, the circuits, which are currently included in one package (`@zk-kit/circuits`), will be divided into several packages per topic, so that versioning will be more consistent with the changes made to a specific circuit. If a circuit has been audited and is considered solid, it cannot have the same version as a circuit being tested.

**Tasks**

- [x] **[zk-kit](https://github.com/privacy-scaling-explorations/zk-kit)**
  - [x] Split IMT libraries (two packages: `imt` and `lean-imt`)
- [x] **[zk-kit.circom](https://github.com/privacy-scaling-explorations/zk-kit.circom)**
  - [x] Create repository
  - [x] Copy circuits from [zk-kit](https://github.com/privacy-scaling-explorations/zk-kit)
  - [x] Move `eddsa-proof` to semaphore extensions
  - [x] Publish new NPM packages
  - [x] Update dependencies on [zk-kit](https://github.com/privacy-scaling-explorations/zk-kit) and Semaphore
  - [x] Remove circuits from [zk-kit](https://github.com/privacy-scaling-explorations/zk-kit)
- [x] **[zk-kit.sol](https://github.com/privacy-scaling-explorations/zk-kit.sol)**
  - [x] Create repository
  - [x] Copy contracts from [zk-kit](https://github.com/privacy-scaling-explorations/zk-kit)
  - [x] Remove contracts from [zk-kit](https://github.com/privacy-scaling-explorations/zk-kit)
- [x] **[zk-kit.noir](https://github.com/privacy-scaling-explorations/zk-kit.noir)**
  - [x] Create repository
  - [x] Copy circuits from [zk-kit](https://github.com/privacy-scaling-explorations/zk-kit)
  - [x] Remove circuits from [zk-kit](https://github.com/privacy-scaling-explorations/zk-kit)
- [x] Add GitPOAPs for new repos
- [x] Update README files and links
