### ISSUE TITLE
Create a package for Circom circuits

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-kit#73]
**Tasks**:

- [ ] Create `@zk-kit/circuits` package
- [ ] Move `lazy-tower.circom` to package
- [ ] Create `lean-imt.circom`
- [ ] Create `poseidon-proof.circom`

**Comment by fabianschu** [comment]
Hey @cedoor, how do you feel about adding Noir circuits as well? I've been working on a Noir implementation of your SMT implementation and was wondering if this repo might be a good place for it to live on.

**Comment by cedoor** [comment]
> Hey @cedoor, how do you feel about adding Noir circuits as well? I've been working on a Noir implementation of your SMT implementation and was wondering if this repo might be a good place for it to live on.

Hey @fabianschu, I think that would be great! We could create 1 folder for each language: `packages/circuits/circom`, `packages/circuits/noir`. How does it sound?

**Comment by fabianschu** [comment]
Sounds great to me. I would create an issue and a PR when I've finished the circuits. Would that make sense?

**Comment by cedoor** [comment]
> Sounds great to me. I would create an issue and a PR when I've finished the circuits. Would that make sense?

Yes, it makes sense. If the [`feat/circuits`](https://github.com/privacy-scaling-explorations/zk-kit/tree/feat/circuits) hasn't been merged into main yet, you can directly merge your PR into it 👍🏽

I've just pushed a commit for supporting multiple languages. You can take a look at the structure here: https://github.com/privacy-scaling-explorations/zk-kit/tree/feat/circuits/packages/circuits.

I don't know Noir but it could be nice to have some scripts for compiling Noir circuits too, like:

https://github.com/privacy-scaling-explorations/zk-kit/blob/3f1ccadfd2fbff1b879a19ab91a40d3d25accd1e/packages/circuits/package.json#L15-L16
