### ISSUE TITLE
Create `@zk-kit/poseidon-proof` package

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-kit#77]
**Tasks**:

- [x] Make package compatible with browsers
- [x] Add reference to circuit
- [x] Add benchmarks to README file
- [x] Add links to Snark artifacts to README file
- [x] Explain what scope and preimage are
- [x] Hash scope and message with `keccak256`
- [x] Document code
- [x] Handle additional possible errors
- [x] Add tests
