### ISSUE TITLE
Check and improve README files

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/zk-kit#83]
**Tasks**:

- [x] Add types of Merkle trees to the `imt` package
- [x] Add circuits to the `circuits` package README file list
- [x] Add `usage` section to the `poseidon-cipher` package

**Comment by 0xjei** [comment]
@cedoor, could you provide more information on this? I am available to work on it if needed 😊

**Comment by cedoor** [comment]
> @cedoor, could you provide more information on this? I am available to work on it if needed 😊

I think the idea was just to re-check the usage sections and add more info/documentation.
